const PHRASES = [
  // Greetings
  { dhivehi: 'އައްސަލާމު ޢަލައިކުމް', phonetic: 'Assalaamu Alaikum', english: 'Hello / Peace be upon you', category: 'greetings' },
  { dhivehi: 'ވަޢަލައިކުމް ސަލާމް', phonetic: 'Wa alaikum salaam', english: 'And peace be upon you (reply)', category: 'greetings' },
  { dhivehi: 'ކިހިނެއް؟', phonetic: 'Kihiney?', english: 'How are you?', category: 'greetings' },
  { dhivehi: 'ރަނގަޅު، ޝުކުރިއްޔާ', phonetic: 'Rangalhu, Shukuriyya', english: 'Fine, thank you', category: 'greetings' },
  { dhivehi: 'ހަމަ ރަނގަޅު', phonetic: 'Hama rangalhu', english: "I'm doing well", category: 'greetings' },
  { dhivehi: 'ވަދާޢު', phonetic: 'Vadhaau', english: 'Goodbye', category: 'greetings' },
  { dhivehi: 'ހެނދުނު ހެވެ', phonetic: 'Hendhunu heve', english: 'Good morning', category: 'greetings' },
  { dhivehi: 'ހަވީރު ހެވެ', phonetic: 'Haveer heve', english: 'Good afternoon', category: 'greetings' },
  { dhivehi: 'ރޭ ހެވެ', phonetic: 'Rey heve', english: 'Good night', category: 'greetings' },
  { dhivehi: 'ހެވިހި ނިދާ', phonetic: 'Hevi nidhaa', english: 'Sleep well', category: 'greetings' },
  { dhivehi: 'ފަހުން ދިމާވާނެ', phonetic: 'Fahun dhimaavaane', english: 'See you later', category: 'greetings' },
  { dhivehi: 'ދިމާވެގެން އުފާވިއްޖެ', phonetic: 'Dhimaavegen ufaavijje', english: 'Nice to meet you', category: 'greetings' },

  // Love & relationships
  { dhivehi: 'ތިޔަ ލޯބި ވެއެ', phonetic: 'Thiya loabi veyey', english: 'I love you', category: 'love' },
  { dhivehi: 'ކަލޭ ހަނދާންވޭ', phonetic: 'Kaley handhaanvey', english: 'I miss you', category: 'love' },
  { dhivehi: 'ތިޔަ ހިތްގައިމު', phonetic: 'Thiya hiththugaimu', english: 'You are beautiful', category: 'love' },
  { dhivehi: 'ތިބާ ދެކިލާ ހިތްވޭ', phonetic: 'Thibaa dhekilaa hiththvey', english: 'I want to see you', category: 'love' },
  { dhivehi: 'ތިބާ ތީ ހާއްސަ', phonetic: 'Thibaa thee haassa', english: 'You are special to me', category: 'love' },
  { dhivehi: 'ހިތް ހަދިޔާ', phonetic: 'Hiththu hadhiyya', english: "My heart's gift (endearment)", category: 'love' },
  { dhivehi: 'ލޯބިވެރިޔާ', phonetic: 'Loabiveriiyaa', english: 'My love / Darling', category: 'love' },
  { dhivehi: 'ތިބާ ހިތަށް ފިނި', phonetic: 'Thibaa hiththah fini', english: 'You bring peace to my heart', category: 'love' },
  { dhivehi: 'ތިބާ ހަނދާންވޭ', phonetic: 'Thibaa handhaanvey', english: "I'm thinking of you", category: 'love' },
  { dhivehi: 'ތިބާ ނުލާ ދިރިނޫޅެވޭ', phonetic: 'Thibaa nulaa dhirinuulsevey', english: "I can't live without you", category: 'love' },
  { dhivehi: 'ތިބާ ތީ ހިތްހަމަ', phonetic: 'Thibaa thee hiththama', english: 'You make me happy', category: 'love' },
  { dhivehi: 'ލޯބިން ގުޅިލާ', phonetic: 'Lobiyn gulilaa', english: 'Call me (with love)', category: 'love' },

  // Daily life
  { dhivehi: 'ހެޔޮ', phonetic: 'Heyo', english: 'OK / Yes / Good', category: 'daily' },
  { dhivehi: 'ނޫން', phonetic: 'Noon', english: 'No', category: 'daily' },
  { dhivehi: 'ޝުކުރިއްޔާ', phonetic: 'Shukuriyya', english: 'Thank you', category: 'daily' },
  { dhivehi: 'ބަލައިލަދީ', phonetic: 'Balailadhee', english: 'Please / Excuse me', category: 'daily' },
  { dhivehi: 'ނޭނގެ', phonetic: 'Neynge', english: "I don't know", category: 'daily' },
  { dhivehi: 'ދޭ', phonetic: 'Dhey', english: 'Please (give me)', category: 'daily' },
  { dhivehi: 'ހިނގާ', phonetic: 'Hingaa', english: "Let's go", category: 'daily' },
  { dhivehi: 'މަޑުކޮށްލާ', phonetic: 'Maadhukoshlaa', english: 'Wait a moment', category: 'daily' },
  { dhivehi: 'ވިސްނިއްޖެ', phonetic: 'Visniijje', english: 'I understand', category: 'daily' },
  { dhivehi: 'ނޭ', phonetic: 'Ney', english: 'There is none', category: 'daily' },
  { dhivehi: 'ލަސްލަހުން ބުނެ', phonetic: 'Laslahun bune', english: 'Please say it slowly', category: 'daily' },
  { dhivehi: 'ތަކުރާރު ކޮށްލަދީ', phonetic: 'Thakuraar koashladhee', english: 'Please repeat that', category: 'daily' },
  { dhivehi: 'މައްސަލައެއް ނެތް', phonetic: 'Massalaeh neiy', english: 'No problem', category: 'daily' },
  { dhivehi: 'ވަރަށް ރަނގަޅު', phonetic: 'Varash rangalhu', english: 'Very good / Great', category: 'daily' },

  // Questions
  { dhivehi: 'ނަމަކީ ކޮބާ؟', phonetic: 'Namakee kobaa?', english: 'What is your name?', category: 'questions' },
  { dhivehi: 'ތިޔައީ ކޮންތާކު ހުރި؟', phonetic: 'Thiyaee konthaakohu?', english: 'Where are you?', category: 'questions' },
  { dhivehi: 'ކިހިނެއް ތި ކިޔަނީ؟', phonetic: 'Kihiney thi kiyanee?', english: 'How do you say this?', category: 'questions' },
  { dhivehi: 'ވަރަށް ދިވެހި ބަހުން ދަސްކުރަން ބޭނުން', phonetic: 'Varash Dhivehi bahun dhaskooran beynu', english: 'I want to learn Dhivehi', category: 'questions' },
  { dhivehi: 'ދިވެހި ބަހުން ތި ވާހަކަ ދައްކަނީ؟', phonetic: 'Dhivehi bahun thi vaahaka dhaikkanee?', english: 'Do you speak Dhivehi?', category: 'questions' },
  { dhivehi: 'އިނގިރޭސި ވާހަކަ ދައްކަނީ؟', phonetic: 'Ingirees vaahaka dhaikkanee?', english: 'Do you speak English?', category: 'questions' },
  { dhivehi: 'ކިހާ ވަރެއް؟', phonetic: 'Kihaa varey?', english: 'How much?', category: 'questions' },
  { dhivehi: 'ކޮންތާކު؟', phonetic: 'Konthaakoo?', english: 'Where?', category: 'questions' },
  { dhivehi: 'ކޮން ގަޑިއެއް؟', phonetic: 'Kon gadhiyey?', english: 'What time is it?', category: 'questions' },
  { dhivehi: 'ކީއްވެ؟', phonetic: 'Keeve?', english: 'Why?', category: 'questions' },

  // Food & drink
  { dhivehi: 'ކެވިދާނެ؟', phonetic: 'Kevidhaane?', english: 'Can we eat?', category: 'food' },
  { dhivehi: 'ވަރަށް މީރު', phonetic: 'Varash meeru', english: 'Very delicious', category: 'food' },
  { dhivehi: 'ފެން ދެވިދާނެ؟', phonetic: 'Fen dhevidhaane?', english: 'Can I have water?', category: 'food' },
  { dhivehi: 'ބަނޑުހައި', phonetic: 'Bandhuhai', english: 'I am hungry', category: 'food' },
  { dhivehi: 'ފައިސާ ދީ', phonetic: 'Faisaa dhee', english: 'The bill, please', category: 'food' },
  { dhivehi: 'ބަނޑު ފުރިއްޖެ', phonetic: 'Bandhu furijje', english: "I'm full", category: 'food' },
  { dhivehi: 'ފެން ބޭނުން', phonetic: 'Fen beynu', english: 'I want water', category: 'food' },
  { dhivehi: 'ކޮފީ ބޭނުން', phonetic: 'Kofi beynu', english: 'I want coffee', category: 'food' },
  { dhivehi: 'ސައި ބޯލަ', phonetic: 'Sai bolaa', english: "Let's have tea", category: 'food' },
  { dhivehi: 'ކާ ހިތްވޭ', phonetic: 'Kaa hiththvey', english: 'I feel like eating', category: 'food' },
  { dhivehi: 'ތަންކޮޅެއް ހިތިވާ', phonetic: 'Thankoles hidhivaa', english: 'A little spicy please', category: 'food' },
  { dhivehi: 'ހިތި ނޭ', phonetic: 'Hidhi ney', english: 'Not spicy', category: 'food' },

  // Numbers
  { dhivehi: 'ސުން', phonetic: 'Sun', english: 'Zero (0)', category: 'numbers' },
  { dhivehi: 'އެއް', phonetic: 'Ek', english: 'One (1)', category: 'numbers' },
  { dhivehi: 'ދެ', phonetic: 'Dhe', english: 'Two (2)', category: 'numbers' },
  { dhivehi: 'ތިން', phonetic: 'Theen', english: 'Three (3)', category: 'numbers' },
  { dhivehi: 'ހަތަރު', phonetic: 'Hatharu', english: 'Four (4)', category: 'numbers' },
  { dhivehi: 'ފަސް', phonetic: 'Fas', english: 'Five (5)', category: 'numbers' },
  { dhivehi: 'ހަ', phonetic: 'Ha', english: 'Six (6)', category: 'numbers' },
  { dhivehi: 'ހަތް', phonetic: 'Hath', english: 'Seven (7)', category: 'numbers' },
  { dhivehi: 'އަށް', phonetic: 'Ash', english: 'Eight (8)', category: 'numbers' },
  { dhivehi: 'ނަވަ', phonetic: 'Nava', english: 'Nine (9)', category: 'numbers' },
  { dhivehi: 'ދިހަ', phonetic: 'Dhiha', english: 'Ten (10)', category: 'numbers' },

  // Travel
  { dhivehi: 'ރަށް', phonetic: 'Rash', english: 'Island', category: 'travel' },
  { dhivehi: 'ކަނޑު', phonetic: 'Kandhu', english: 'Sea / Ocean', category: 'travel' },
  { dhivehi: 'ގޮނޑުދޮށް', phonetic: 'Gondhudhoash', english: 'Beach', category: 'travel' },
  { dhivehi: 'ދޯނި', phonetic: 'Dhoani', english: 'Traditional boat', category: 'travel' },
  { dhivehi: 'ވައިގެ ބަނދަރު', phonetic: 'Vaige bandharu', english: 'Airport', category: 'travel' },
  { dhivehi: 'ހޮޓެލް', phonetic: 'Hotel', english: 'Hotel', category: 'travel' },
  { dhivehi: 'ސަލާމަތްކޮށްދީ', phonetic: 'Salaamath koshdhee', english: 'Help me!', category: 'travel' },
  { dhivehi: 'ބަލިވެ', phonetic: 'Balivey', english: "I'm sick / unwell", category: 'travel' },
  { dhivehi: 'ހޮސްޕިޓަލް ކޮބާ؟', phonetic: 'Hospital kobaa?', english: 'Where is the hospital?', category: 'travel' },
  { dhivehi: 'ޓެކްސީ ބޭނުން', phonetic: 'Taxi beynu', english: 'I need a taxi', category: 'travel' },
  { dhivehi: 'ދުރު؟', phonetic: 'Dhuru?', english: 'Is it far?', category: 'travel' },
  { dhivehi: 'ފާހާނާ ކޮބާ؟', phonetic: 'Faahana kobaa?', english: 'Where is the bathroom?', category: 'travel' },

  // Emotions & feelings
  { dhivehi: 'އުފާވޭ', phonetic: 'Ufaavey', english: "I'm happy", category: 'emotions' },
  { dhivehi: 'ދެރަވޭ', phonetic: 'Dheravey', english: "I'm sad", category: 'emotions' },
  { dhivehi: 'ވަރުބަލިވޭ', phonetic: 'Varubalivey', english: "I'm tired", category: 'emotions' },
  { dhivehi: 'ބިރުވެ', phonetic: 'Biruvet', english: "I'm scared", category: 'emotions' },
  { dhivehi: 'ރުޅިއަ', phonetic: 'Rulia', english: "I'm angry", category: 'emotions' },
  { dhivehi: 'ހިތްހަމަ ޖެހިއްޖެ', phonetic: 'Hiththama jehijje', english: "I'm content / at peace", category: 'emotions' },
  { dhivehi: 'ލަދުވެ', phonetic: 'Ladhuvey', english: "I'm embarrassed", category: 'emotions' },
  { dhivehi: 'ހައިރާންވޭ', phonetic: 'Hairaan vey', english: "I'm surprised", category: 'emotions' },
  { dhivehi: 'ވަރަށް ލޯބި', phonetic: 'Varash loabi', english: 'So lovely / adorable', category: 'emotions' },
  { dhivehi: 'ހިތްވަރު ލިބިއްޖެ', phonetic: 'Hiththvaru libijje', english: "I'm proud / I feel brave", category: 'emotions' },

  // Family & people
  { dhivehi: 'މަންމަ', phonetic: 'Mamma', english: 'Mother / Mum', category: 'family' },
  { dhivehi: 'ބައްޕަ', phonetic: 'Bappa', english: 'Father / Dad', category: 'family' },
  { dhivehi: 'ދައްތަ', phonetic: 'Dhaitta', english: 'Older sister', category: 'family' },
  { dhivehi: 'ބޭބެ', phonetic: 'Beybey', english: 'Older brother', category: 'family' },
  { dhivehi: 'ކޮއްކޮ', phonetic: 'Koakko', english: 'Younger sibling', category: 'family' },
  { dhivehi: 'ރަހްމަތްތެރިޔާ', phonetic: 'Rahmaththeriyaa', english: 'Friend', category: 'family' },
  { dhivehi: 'ފިރިމީހާ', phonetic: 'Firi meehaa', english: 'Husband', category: 'family' },
  { dhivehi: 'އަންހެނުން', phonetic: 'Anhenun', english: 'Wife', category: 'family' },
  { dhivehi: 'ތުއްތު ދަރި', phonetic: 'Thuththu dari', english: 'Baby / little one', category: 'family' },
  { dhivehi: 'ޢާއިލާ', phonetic: 'Aaila', english: 'Family', category: 'family' },
];
